### ISSUE TITLE
RuntimeError: Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany

### ISSUE THREAD

**Issue by disign-ming** [richardaecn/cvpr18-inaturalist-transfer#5]
INFO:tensorflow:global step 2810: loss = 2.0889 (0.639 sec/step)
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
Traceback (most recent call last):
  File "train.py", line 603, in <module>
    tf.app.run()
  File "/home/design/anaconda3/envs/tensorflow019/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 599, in main
    session_config=session_config)
  File "/home/design/anaconda3/envs/tensorflow019/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 785, in train
    ignore_live_threads=ignore_live_threads)
  File "/home/design/anaconda3/envs/tensorflow019/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/design/anaconda3/envs/tensorflow019/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 397, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: QueueRunnerThread-dummy_queue-sync_token_q_EnqueueMany

**Comment by lxl910915** [comment]
same problem

**Comment by shnamin** [comment]
has anyone found how to resolve this? Thanks

**Comment by shnamin** [comment]
I figured this occurs when retraining the mobilenet v3. Please let us know if there is a workaround. I tried with tensorflow 1.14 and 1.15 and the error occurs in both
